server {
    listen 8080;
    server_name _;

    root /downloads;
    autoindex on;
    charset utf-8;
    sendfile on;
    tcp_nopush on;
    etag on;
    max_ranges 1;

    location / {
        try_files $uri =404;
        limit_except GET HEAD {
            deny all;
        }
    }
}
